export const GET_PRODUCT_REQUEST = "GET_PRODUCT_REQUEST"
export const GET_PRODUCT_SUCCES = "GET_PRODUCT_SUCCES"
export const GET_PRODUCT_FAILED = "GET_PRODUCT_FAILED"

export const GET_PRODUCT_REVIEW_REQUEST = "GET_PRODUCT_REVIEW_REQUEST"
export const GET_PRODUCT_REVIEW_SUCCES = "GET_PRODUCT_REVIEW_SUCCES"
export const GET_PRODUCT_REVIEW_FAILED = "GET_PRODUCT_REVIEW_FAILED"

export const PRODUCT_UPDATE_REVIEW_REQUEST = "PRODUCT_UPDATE_REVIEW_REQUEST"
export const PRODUCT_UPDATE_REVIEW_SUCCES = "PRODUCT_UPDATE_REVIEW_SUCCES"
export const PRODUCT_UPDATE_REVIEW_FAILED = "PRODUCT_UPDATE_REVIEW_FAILED"

export const PRODUCT_REVIEW_REMOVE_REQUEST = "PRODUCT_REVIEW_REMOVE_REQUEST"
export const PRODUCT_REVIEW_REMOVE_SUCCES = "PRODUCT_REVIEW_REMOVE_SUCCES"
export const PRODUCT_REVIEW_REMOVE_FAILED = "PRODUCT_REVIEW_REMOVE_FAILED"