version: "3"
services:
  node-app:
    image: node-app
    ports:
      - "8300:8300"
    depends_on:
      - mongo
    networks:
      - mern-app
  react-app:
    image: react-app
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - mern-app
  mongo:
    image: mongo:3.6.19-xenial
    ports:
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db   
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
